aws:
  region: us-east-1
services:
  s3:
    bucket: ai-ppt-assistant-dev-presentations-52de98b4
    templates_bucket: ai-ppt-assistant-dev-templates
  dynamodb:
    table: ai-ppt-assistant-dev-sessions
    checkpoints_table: ai-ppt-assistant-dev-checkpoints
  bedrock:
    model_id: anthropic.claude-4-0
    nova_model_id: stability.stable-diffusion-xl-v1
performance:
  max_concurrent_downloads: 3
  max_concurrent_images: 3
  max_concurrent_slides: 5
  image_download_timeout: 10
  cache_ttl_seconds: 3600
  max_slides: 20
  max_image_size_mb: 10
  batch_size: 3
  checkpoint_ttl_hours: 24
  max_checkpoints_per_task: 50
  default_seconds_per_slide: 60
  max_search_results: 10
  max_template_size_mb: 50
  default_image_size: 1024x768
security:
  vpc_enabled: false
  enable_rekognition: false
monitoring:
  log_level: DEBUG
  download_expiry_seconds: 3600
metadata:
  environment: dev
  last_updated: '2025-01-15'
unmapped_environment_variables:
  use_config_files: true
  config_migration_mode: auto
