aws:
  region: us-east-1
services:
  s3:
    bucket: ai-ppt-assistant-presentations
    templates_bucket: ai-ppt-assistant-templates
  dynamodb:
    table: ai-ppt-assistant-sessions
    checkpoints_table: ai-ppt-assistant-checkpoints
  bedrock:
    model_id: us.anthropic.claude-opus-4-20250514-v1:0  # Claude 4.0 for content generation
    orchestrator_model_id: us.anthropic.claude-opus-4-1-20250805-v1:0  # Claude 4.1 for orchestration
    nova_model_id: amazon.nova-canvas-v1:0  # Nova for image generation
performance:
  max_concurrent_downloads: 3
  max_concurrent_images: 3
  max_concurrent_slides: 5
  image_download_timeout: 10
  cache_ttl_seconds: 3600
  max_slides: 20
  max_image_size_mb: 10
  batch_size: 3
  checkpoint_ttl_hours: 24
  max_checkpoints_per_task: 50
  default_seconds_per_slide: 60
  max_search_results: 10
  max_template_size_mb: 50
  default_image_size: 1024x768
security:
  vpc_enabled: true
  enable_rekognition: false
  encryption_enabled: true
monitoring:
  log_level: DEBUG
  download_expiry_seconds: 3600
  enable_xray: true
  enable_monitoring: true
metadata:
  environment: prod
  last_updated: '2025-01-15'
unmapped_environment_variables:
  use_config_files: true
  config_migration_mode: auto
